micronaut:
  application:
    name: demoDataTenancy
  data:
    multi-tenancy:
      mode: DATASOURCE
  multitenancy:
    tenantresolver:
      httpheader:
        enabled: true

datasources:
  2018:
    url: jdbc:mysql://localhost:3306/2018
    username: root
    password: cibertec
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: NONE #CREATE_DROP
    dialect: MYSQL
  2019:
    url: jdbc:mysql://localhost:3306/2019
    username: root
    password: cibertec
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: NONE #CREATE_DROP
    dialect: MYSQL