micronaut:
  application:
    name: demoDataTenancy

datasources:
  default:
    url: jdbc:mysql://localhost:3306/2018
    username: root
    password: cibertec
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: NONE #CREATE_DROP
    dialect: MYSQL
